### ISSUE TITLE
Can you do Csharp version of your code?

### ISSUE THREAD

**Issue by alphashow** [mszula/php-newcamd#1]
Hello Mateusz,

Can you do C# (CSharp) version of your code?

Also can you make CCcam tester as newcamd? because that is very helpful for us

Thank you

**Comment by mszula** [comment]
Hi,

To be honest, I don't know C# so I can't make the library in this language.

With reference to CCcam client in PHP, I can do that, but is takes many time due to lack of complete protocol documentation.
